apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vs-seeder.fullname" . }}-config
data:
  {{ (tpl (.Files.Glob "files/cache/mapcache.xml").AsConfig . ) | nindent 2}}
  {{ (tpl (.Files.Glob "files/seeder/seeder-config.yaml").AsConfig . ) | nindent 2}}
