{{- if .Values.client.ingress.enabled -}}
{{- $fullName := include "vs-client.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vs-client.labels" . | nindent 4 }}
  {{- with .Values.client.ingress.annotations | default .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- end }}
spec:
  {{- if .Values.client.ingress.tls | default .Values.global.ingress.tls }}
  tls:
    {{- range .Values.client.ingress.tls | default .Values.global.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.client.ingress.hosts | default .Values.global.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - pathType: Prefix
          {{- if $.Values.global.ingress.prefix.enabled }}
          path: /{{ $.Values.global.ingress.prefix.value }}/(.*)
          {{- else }}
          path: /(.*)
          {{- end }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: 80
    {{- end }}
{{- end -}}
