apiVersion: v1
kind: Service
metadata:
  name: {{ include "vs-client.fullname" . }}
  labels:
    {{- include "vs-client.labels" . | nindent 4 }}
    app.kubernetes.io/service: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "vs-client.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/service: client
