apiVersion: v1
kind: Service
metadata:
  name: aurora-explorer-view-server-renderer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: aurora-explorer-view-server-renderer
