project: default
source:
  repoURL: 'https://github.com/james-hinton/aurora-explorer-eoxserver.git'
  path: helm/
  targetRevision: HEAD
destination:
  namespace: default
  name: in-cluster
syncPolicy:
  automated:
    selfHeal: true
