apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vs-preprocessor.fullname" . }}-config
data:
  {{ (tpl (.Files.Glob "files/preprocessor/preprocessor-config.yaml").AsConfig . ) | nindent 2 }}
