# environment variables which are needed for the services
global:
  env:
    DEBUG: "true"
    GDAL_DISABLE_READDIR_ON_OPEN: "TRUE"
    COLLECT_STATIC: "false"
    GDAL_PAM_ENABLED: "NO"

    # NOTE: The following credentials are not real and are used for demonstration purposes only
    DB_NAME: dbname
    DB_PORT: "5432"
    DB_PW: dbpw
    DB_USER: dbuser
    POSTGRES_DB: dbname
    POSTGRES_PASSWORD: dbpw
    POSTGRES_USER: dbuser

    DJANGO_MAIL: office@eox.at
    DJANGO_PASSWORD: djangopw
    DJANGO_USER: djangouser
    REDIS_PORT: "6379"
    REDIS_PREPROCESS_QUEUE_KEY: preprocess_queue
    REDIS_REGISTER_QUEUE_KEY: register_queue
    REDIS_SEED_QUEUE_KEY: seed_queue
    REDIS_HARVESTER_QUEUE_KEY: harvester_queue

  dbsync:
    create: true
    replace: false
    delete: false

  storage:
    data:
      data:
        type: "directory"
        root_directory: "/data"

      # It seems EoXServer S3-integration currently is having problems, if you want to use S3 then mount your own S3FS.
      data2:
        type: "s3"
        bucket: "aurora-explorer-data"
        endpoint_url: "https://aurora-explorer-data.s3.eu-west-2.amazonaws.com"
        access_key_id: "NOTREAL"
        secret_access_key: "NOTREAL"
        region_name: "eu-west-2"

    cache:
      type: local

  collections:
    AURORA_INTENSITY:
      product_types:
        - AURORA
      coverage_types:
        - INTENSITY

  productTypes:
    - name: AURORA
      defaultBrowse: INTENSITY
      browses:
        INTENSITY:
          red:
            expression: intensity
            range:
              - 1
              - 22
            nodata: 0
      collections:
        - AURORA_INTENSITY

  defaultLayer:

  layers:
    - id: AURORA_INTENSITY
      title: Aurora Intensity Measurements
      abstract: Aurora intensity measurements visualized.
      displayColor: "#00FF00"
      grids:
        - name: WGS84
          zoom: 13
      search:
        histogramBinCount: 15
        histogramThreshold: 80
      download: &defaultDownloadClient
        wcsExtensionsKVPParameters:
          exceptions: "text/html"
        wcsExtensionsXMLParameters:
          "eoxs:exceptions": "text/html"
        wcsExtensionsXMLNamespaces:
          eoxs: "http://eoxserver.org/eoxs/1.0"
      detailsDisplay:
        id: "aurora_intensity"
        visible: true
        protocol: "WMS"
        urls: baseUrlsOws
        version: "1.3.0"
        format: "image/png"
        gutter: 2
        projection: "EPSG:4326"

  overlayLayers: []

  coverageTypes:
    - name: INTENSITY
      bands:
        - definition: "http://www.opengis.net/def/property/OGC/0/Radiance"
          description: Intensity
          identifier: INTENSITY
          name: Intensity
          nil_values:
            - reason: "http://www.opengis.net/def/nil/OGC/0/unknown"
              value: -9999
          uom: "W.m-2.Sr-1"
      data_type: Float32
  disableDefaultCoverageTypes: false
  rasterStyles: []
  metadata: {}
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: vs.local
    tls:
      - hosts:
          - vs.local
    prefix:
      enabled: false

# general gdal related settings
gdal:
  allowedExtensions:
    enabled: false # This will be null in the future to enforce overriding
    value: ".tif,.xml"

database:
  #### SHOULD BE CHANGED IN PROD ####
  auth:
    username: dbuser
    password: dbpw
    database: dbname
    postgresPassword: dbpgpw
  primary:
    persistence:
      enabled: false
      existingClaim: data-access-db
    extendedConfiguration: "max_connections=3000"
    initdb:
      scripts:
        enablePostgis.sh: |
          echo "Enabling postgis"
          PGPASSWORD="${POSTGRES_POSTGRES_PASSWORD}" psql -U postgres -d "${POSTGRES_DB}" -c "CREATE EXTENSION postgis;"
  replicaCount: 1
  resources:
    limits:
      cpu: "1.5"
      memory: 6Gi
    requests:
      cpu: "0.1"
      memory: 0.5Gi
  affinity: {}

redis:
  usePassword: false
  persistence:
    existingClaim: data-access-redis
  master:
    persistence:
      enabled: true
      storageClass: managed-nfs-storage
  cluster:
    enabled: false

client:
  replicaCount: 1
  nameOverride:
  fullNameOverride:

  image:
    repository: registry.gitlab.eox.at/vs/vs/client
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  config:
    timeDomain:
      - "2019-01-01T00:00:00Z"
      - "today"
    displayTimeDomain:
      - "2019-01-01T00:00:00Z"
      - "2020-12-31T23:59:59Z"
    displayInterval: P1096D
    selectedTimeDomain:
      - "2020-08-01T00:00:00Z"
      - "2020-08-31T23:59:59Z"
    selectableInterval: P1096D
    center:
      - 12
      - 49
    zoom: 5
    minZoom: 1
    maxZoom: 17
    serviceUrl: ""
    clientHeaderHTML: '<header id="header" style="width: 100%; height:70px; position:absolute;"><h3 style="width:100%; text-align:center; color: #006699;">PRISM View Server (PVS) Client powered by <a href="//eox.at"><img src="//eox.at/EOX_Logo.svg" alt="EOX" style="height:25px;margin-left:10px"/></a></h3></header>'
    clientHeaderHeight: 70px
    leftPanelOpen: true
    rightPanelOpen: true
    leftPanelTabIndex: 1
    rightPanelTabIndex: 0
    tutorial: once
    enable3D: false
    mapMode: 2D
    terrainUrl: ""
    uploadEnabled: true
    areaFilterLayerExtent: false
    selectFilesDownloadEnabled: false
    downloadEnabled: true
    searchEnabled: true
    disableTimeSlider: false
    enableDynamicHistogram: false
    timeSliderAlternativeBrush: false
    searchDebounceTime: 500
    language: "en"
    timeSliderControls: true
    enableSingleLayerMode: false
    maxTooltips: 1
    disableSearchParams: false
    enableGetEOCoverageSet: true
    maxSocketsPerHostSearch: 6
    eoxserverDownloadEnabled: false
    footprintFillColor: "rgba(0, 0, 0, 0.2)"
    footprintStrokeColor: "rgba(0, 0, 0, 1)"
    filterFillColor: "rgba(0, 165, 255, 0)"
    filterStrokeColor: "rgba(0, 165, 255, 1)"
    filterOutsideColor: "rgba(0, 0, 0, 0.5)"
    selectedFootprintFillColor: "rgba(255, 0, 0, 0.2)"
    selectedFootprintStrokeColor: "rgba(255, 0, 0, 1)"
    highlightFillColor: "rgba(246, 182, 0, 0.5)"
    highlightStrokeColor: "rgba(246, 182, 0, 1)"
    highlightStrokeWidth: 3
    translations:
      {
        "en":
          {
            "Cloud Cover": "Cloud coverage (%)",
            "Error: NoApplicableCode": "Search timed out. Please refine the filter criteria.",
          },
      }
    filterSettings:
      time:
        hidden: true
    downloadFormats:
      [
        { "name": "TIFF", "mimeType": "image/tiff" },
        { "name": "JPEG 2000", "mimeType": "image/jp2" },
        { "name": "HDF", "mimeType": "application/x-hdf" },
      ]
    multiDownloadFormats:
      [
        { "name": "ZIP", "mimeType": "application/zip" },
        { "name": "TAR", "mimeType": "application/tar" },
        { "name": "GZIP", "mimeType": "application/gzip" },
      ]
    downloadProjections:
      [
        {
          "name": "WGS-84",
          "identifier": "http://www.opengis.net/def/crs/EPSG/0/4326",
        },
        {
          "name": "Web Mercator",
          "identifier": "http://www.opengis.net/def/crs/EPSG/0/3857",
        },
        {
          "name": "ETRS89 / LAEA Europe",
          "identifier": "http://www.opengis.net/def/crs/EPSG/0/3035",
        },
      ]
    downloadInterpolations:
      [
        {
          "name": "Bilinear",
          "identifier": "http://www.opengis.net/def/interpolation/OGC/1/bilinear",
        },
        {
          "name": "Nearest Neighbour",
          "identifier": "http://www.opengis.net/def/interpolation/OGC/1/nearest-neighbour",
        },
        {
          "name": "Average",
          "identifier": "http://www.opengis.net/def/interpolation/OGC/1/average",
        },
      ]
    baseLayers:
      [
        {
          "id": "terrain-light",
          "displayName": "EOX Terrain-Light",
          "display":
            {
              "id": "terrain-light",
              "visible": true,
              "protocol": "WMTS",
              "urls":
                [
                  "//a.s2maps-tiles.eu/wmts/",
                  "//b.s2maps-tiles.eu/wmts/",
                  "//c.s2maps-tiles.eu/wmts/",
                  "//d.s2maps-tiles.eu/wmts/",
                  "//e.s2maps-tiles.eu/wmts/",
                ],
              "description": '<div><b>EOX Terrain Light</b> Tile service provides an idea of land usage and topography. It is based on following public data: <ul class="list-unstyled"><li><a href="//openstreetmap.org/copyright" target="_blank">OpenStreetMap</a></li><li><a href="//naturalearthdata.com/about/terms-of-use/" target="_blank">NaturalEarth public domain</a></li><li><a href="//gebco.net" target="_blank">GEBCO</a></li><li><a href="//asterweb.jpl.nasa.gov/gdem.asp" target="_blank">ASTER GDEM</a></li><li><a href="//lta.cr.usgs.gov/GTOPO30" target="_blank">GTOPO30</a></li></ul><p>More information on: <a href="//s2maps.eu/" target="_blank">s2maps.eu</a> and <a href="//maps.eox.at" target="_blank">maps.eox.at</a></p></div>',
              "infoPopup:": true,
              "matrixSet": "WGS84",
              "format": "image/png",
              "projection": "EPSG:4326",
              "style": "default",
              "attribution": 'Terrain-Light { Data &copy; <a href="//openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors and <a href=''javascript:;'' onClick=''toggle(terrain_attribution)''>others</a>, Rendering &copy; <a href="//eox.at" target="_blank">EOX</a> }',
            },
        },
        {
          "id": "terrain",
          "displayName": "EOX Terrain",
          "display":
            {
              "id": "terrain",
              "visible": false,
              "protocol": "WMTS",
              "urls":
                [
                  "//a.s2maps-tiles.eu/wmts/",
                  "//b.s2maps-tiles.eu/wmts/",
                  "//c.s2maps-tiles.eu/wmts/",
                  "//d.s2maps-tiles.eu/wmts/",
                  "//e.s2maps-tiles.eu/wmts/",
                ],
              "infoPopup:": true,
              "description": '<div><b>EOX Terrain</b> Tile service provides an idea of land usage and topography. It is based on following public data: <ul class="list-unstyled"><li><a href="//openstreetmap.org/copyright" target="_blank">OpenStreetMap</a></li><li><a href="//naturalearthdata.com/about/terms-of-use/" target="_blank">NaturalEarth public domain</a></li><li><a href="//nasa.gov" target="_blank">NASA SRTM</a></li><li>EUDEM</li><li><a href="//lta.cr.usgs.gov/GTOPO30" target="_blank">GTOPO30</a></li><li><a href="//due.esrin.esa.int/page_globcover.php" target="_blank">GlobCover</a></li></ul><p>More information on: <a href="//s2maps.eu/" target="_blank">s2maps.eu</a> and <a href="//maps.eox.at" target="_blank">maps.eox.at</a></p></div>',
              "matrixSet": "WGS84",
              "format": "image/png",
              "projection": "EPSG:4326",
              "style": "default",
              "attribution": 'Terrain { Data &copy; <a href="//openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors and <a href=''javascript:;'' onClick=''toggle(terrain_attribution)''>others</a>, Rendering &copy; <a href="//eox.at" target="_blank">EOX</a> }',
            },
        },
        {
          "id": "s2cloudless",
          "displayName": "EOX Sentinel-2 cloudless",
          "display":
            {
              "id": "s2cloudless-2021",
              "visible": false,
              "protocol": "WMTS",
              "urls":
                [
                  "//a.s2maps-tiles.eu/wmts/",
                  "//b.s2maps-tiles.eu/wmts/",
                  "//c.s2maps-tiles.eu/wmts/",
                  "//d.s2maps-tiles.eu/wmts/",
                  "//e.s2maps-tiles.eu/wmts/",
                ],
              "infoPopup:": true,
              "description": '<div><p><b>EOX Sentinel-2 cloudless</b> Tile service providing an (almost) cloudless map of the world, crafted by EOX.</p><p>Uses Sentinel-2 L2A data for land surfaces, coastal waters and some islands as specified by the ESA (varies throughout the years) and a custom bathymetry render fills the oceans.</p><p>More information on: <a href="//s2maps.eu/" target="_blank">s2maps.eu</a> and <a href="//maps.eox.at" target="_blank">maps.eox.at</a></p></div>',
              "matrixSet": "WGS84",
              "format": "image/png",
              "projection": "EPSG:4326",
              "style": "default",
              "attribution": '<a xmlns:dct="//purl.org/dc/terms/" href="//s2maps.eu" property="dct:title">Sentinel-2 cloudless - //s2maps.eu</a> by <a xmlns:cc="//creativecommons.org/ns#" href="s://eox.at" property="cc:attributionName" rel="cc:attributionURL">EOX IT Services GmbH</a> (Contains modified Copernicus Sentinel data 2021)',
            },
        },
      ]
    overlayLayers:
      [
        {
          "id": "overlay_base",
          "displayName": "EOX Borders and Labels",
          "display":
            {
              "id": "overlay_base",
              "visible": false,
              "protocol": "WMTS",
              "urls":
                [
                  "//a.s2maps-tiles.eu/wmts/",
                  "//b.s2maps-tiles.eu/wmts/",
                  "//c.s2maps-tiles.eu/wmts/",
                  "//d.s2maps-tiles.eu/wmts/",
                  "//e.s2maps-tiles.eu/wmts/",
                ],
              "infoPopup:": true,
              "description": '<div><b>EOX Overlay base</b> Tile service shows labels and line features like borders or streets to provide more detailed information. It is based on following public data: <ul class="list-unstyled"><li><a href="//openstreetmap.org/copyright" target="_blank">OpenStreetMap</a></li><li><a href="//naturalearthdata.com/about/terms-of-use/" target="_blank">NaturalEarth public domain</a></li></ul><p>More information on: <a href="//s2maps.eu/" target="_blank">s2maps.eu</a> and <a href="//maps.eox.at" target="_blank">maps.eox.at</a></p></div>',
              "matrixSet": "WGS84",
              "style": "default",
              "format": "image/png",
              "projection": "EPSG:4326",
              "attribution": 'Overlay { Data &copy; <a href="//openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors, Rendering &copy; <a href="//eox.at" target="_blank">EOX</a> and <a href="//github.com/mapserver/basemaps" target="_blank">MapServer</a> }',
            },
        },
      ]
    tutorialHrefHtml: "https://vs.pages.eox.at/documentation/user/main"
    tutorialHrefPDF: "https://vs.pages.eox.at/documentation/user/View-Server_-_User-Guide.pdf"
  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.1
      memory: 100Mi

  affinity: {}

  livenessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8080
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  ingress:
    enabled: true

cache:
  replicaCount: 1
  nameOverride:
  fullNameOverride:
  image:
    repository: registry.gitlab.eox.at/vs/vs/cache
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  config:
    wmsEnabled: true
    wmtsEnabled: true
    connectionTimeout: 10
    timeout: 120
    expires: 3600
    key: /{tileset}/{grid}/{dim}/{z}/{x}/{y}.{ext}
    extra_key: /{tileset}/{grid}/{z}/{x}/{y}.{ext}
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.1
      memory: 100Mi
  livenessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8080
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  affinity: {}
  ingress:
    enabled: true

renderer:
  nameOverride:
  fullNameOverride:

  image:
    repository: registry.gitlab.eox.at/vs/vs/core
    pullPolicy: IfNotPresent
    tag: ""

  livenessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 80
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  imagePullSecrets: []

  replicaCount: 1
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 1.5
      memory: 6Gi
    requests:
      cpu: 0.5
      memory: 0.5Gi

  affinity: {}

  # needs access to aurora-test-data
  volumes:
    - name: local-storage
      hostPath:
        path: /minikube-host/Projects/aurora-test-data
        type: Directory
  volumeMounts:
    - name: local-storage
      mountPath: /data

  ingress:
    enabled: true

  config:
    enableHttpAccess: false

dbsync:
  nameOverride:
  fullNameOverride:

  image:
    repository: registry.gitlab.eox.at/vs/vs/core
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  replicaCount: 1

  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.25
      memory: 0.25Gi

  affinity: {}

  volumeMounts: []
  volumes: []

preprocessor:
  replicaCount: 0
  nameOverride:
  fullNameOverride:

  image:
    repository: registry.gitlab.eox.at/vs/vs/preprocessor
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  secrets: []

  resources:
    limits:
      cpu: 1.5
      memory: 6Gi
    requests:
      cpu: 0.5
      memory: 0.5Gi

  affinity: {}

  config:
    collections: {} # Mapping of collections to process
    filesystems: {} # Mapping of filesystem configurations
    paths: {} # Mapping of paths
    processors: {} # Mapping of processor configurations

  volumes: []
  volumeMounts: []

registrar:
  replicaCount: 1
  nameOverride:
  fullNameOverride:

  image:
    repository: registry.gitlab.eox.at/vs/vs/core
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  resources:
    limits:
      cpu: 1.5
      memory: 6Gi
    requests:
      cpu: 0.5
      memory: 0.5Gi

  affinity: {}

  volumes:
    - name: local-storage
      hostPath:
        path: /minikube-host/Projects/aurora-test-data
        type: Directory
  volumeMounts:
    - name: local-storage
      mountPath: /data

  config:
    disableDefaultRoute: false
    eoxserverInstanceBasePath: "/var/www/pvs/dev"
    eoxserverInstanceName: "pvs_instance"
    defaultQueue: "register"
    defaultSuccessQueue:
    defaultErrorQueue:
    defaultReplace: true
    defaultBackends: []
    defaultHandlers:
    routes: {}

harvester:
  replicaCount: 1
  nameOverride:
  fullNameOverride:
  image:
    repository: registry.gitlab.eox.at/vs/vs/harvester
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  secrets: []
  config:
    harvesters: {}
  resources:
    limits:
      cpu: 1.5
      memory: 6Gi
    requests:
      cpu: 0.5
      memory: 0.5Gi
  affinity: {}
  volumes: []
  volumeMounts: []

scheduler:
  replicaCount: 1
  nameOverride:
  fullNameOverride:
  image:
    repository: registry.gitlab.eox.at/vs/vs/scheduler
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  config:
    schedules: []
  resources:
    limits:
      cpu: 1.5
      memory: 6Gi
    requests:
      cpu: 0.5
      memory: 0.5Gi
  affinity: {}
  volumes: []
  volumeMounts: []

seeder:
  replicaCount: 1
  nameOverride:
  fullNameOverride:
  image:
    repository: registry.gitlab.eox.at/vs/vs/seeder
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  config:
    wmsEnabled: true
    wmtsEnabled: true
    connectionTimeout: 10
    timeout: 120
    expires: 3600
    key: /{tileset}/{grid}/{dim}/{z}/{x}/{y}.{ext}
    cache_extra_key: /{tileset}/{grid}/{z}/{x}/{y}.{ext}
    # seeder-specific config
    minzoom: 0
    maxzoom: 10
    collection_grids: {}
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.1
      memory: 100Mi
  affinity: {}
