apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-django-secret-key
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.global.env.DJANGO_SECRET_KEY | default (randAlphaNum 36) | b64enc }}
