apiVersion: v1
kind: Service
metadata:
  name: {{ include "vs-renderer.fullname" . }}
  labels:
    {{- include "vs-renderer.labels" . | nindent 4 }}
    app.kubernetes.io/service: renderer
spec:
  type: {{ .Values.renderer.service.type }}
  ports:
    - port: {{ .Values.renderer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vs-renderer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/service: renderer
